config/routes.rb
Rails.application.routes.draw do
  resources(:records, param: :slug)

  root('records#index')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  validates_presence_of(:artist, :title, :year)
  validates_uniqueness_of(:slug)
  before_save(:create_slug)

  def create_slug
    self.slug = title.downcase.gsub(' ', '-')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action(:find_record, only: %i[show edit update destroy])

  def index
    @records = Record.all
  end

  def new
    @record = Record.new

    render(
      :new,
      locals: {
        method: :post,
        url: records_path
      }
    )
  end

  def create
    @record = Record.new(record_params)

    return render :new unless @record.save

    flash[:success] = 'Record Created!'
    redirect_to(record_path(@record.slug))
  end

  def show; end

  def edit
    render(
      :edit,
      locals: {
        method: :patch,
        url: record_path(@record.slug)
      }
    )
  end

  def update
    if @record.update(record_params)
      flash[:success] = 'Record Updated'
      return redirect_to record_path(@record.slug)
    end

    flash[:warning] = 'Something broken'
    render :edit
  end

  def destroy
    @record.delete

    flash[:success] = "#{@record.title} Deleted"
    redirect_to(records_path)
  end

  private

  def find_record
    @record = Record.find_by(slug: params[:slug])
  end

  def record_params
    params.require(:record).permit(
      :artist,
      :title,
      :year,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:success].present? %>
  <p>
    <%= flash[:success] %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<h1>Jonic's Records</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinyl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: @record, method: method, url: url) do |form| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% @record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h2>Editing <em><%= @record.title %></em></h2>
<%= render(partial: 'records/form', locals: { method: method, url: url}) %>

app/views/records/index.html.erb
<p>
  <%= link_to('New Record', new_record_path) %>
</p>

<ul>
<% @records.each do |record| %>
  <li>
    <%= record.title %>
    <%= link_to('View me', record_path(record.slug)) %>
  </li>
<% end %>
</ul>

app/views/records/new.html.erb
<h2>Create New Record</h2>
<%= render(partial: 'records/form', locals: { method: method, url: url}) %>

app/views/records/show.html.erb
<p>
  <%= link_to('Back', records_path) %>
  &middot;
  <%= link_to('Edit', edit_record_path(@record.slug)) %>
  &middot;
  <%= link_to('Destroy', record_path(@record.slug), method: :delete, data: { confirm: 'Are you sure?' }) %>
</p>

<h2><%= @record.title %></h2>
<p>Release year: <%= @record.year %></p>